#include "Effects.h"

void Effects::begin(){_pixels.begin();_pixels.clear();_pixels.show();ledcSetup(PIEZO_CHANNEL,2000,8);ledcAttachPin(PIEZO_PIN,PIEZO_CHANNEL);} 
void Effects::update(){updateAnimation();updateOverlay();updateBlinker();updateBeep();render();}
void Effects::setAnim(AnimationMode mode,bool storeOld){if(storeOld)_oldAnim=mode;_anim=mode;_animStep=0;_animLastUpdate=millis();}
void Effects::setAnimIdle(bool s){setAnim(ANIM_IDLE,s);} void Effects::setAnimError(bool s){setAnim(ANIM_ERROR,s);} void Effects::setAnimLine(bool s){setAnim(ANIM_LINE,s);} void Effects::setAnimGame(bool s){setAnim(ANIM_GAME,s);} void Effects::setAnimFree(bool s){setAnim(ANIM_FREE,s);} void Effects::setAnimObstacle(bool s){setAnim(ANIM_OBSTACLE,s);} void Effects::setAnimStop(bool s){setAnim(ANIM_STOP,s);} void Effects::resetAnim(){setAnim(_oldAnim,false);}
void Effects::setOverlayRfid(){_overlay=OVERLAY_RFID;_overlayStep=0;_overlayLastUpdate=millis();_overlayUntil=millis()+800;setBeep(1800,80);} void Effects::setOverlaySuccess(){_overlay=OVERLAY_SUCCESS;_overlayStep=0;_overlayLastUpdate=millis();_overlayUntil=millis()+250;setBeep(2600,120);} void Effects::setOverlayBoot(){_overlay=OVERLAY_BOOT;_overlayStep=0;_overlayLastUpdate=millis();_overlayUntil=millis()+1500;setBeep(1200,100);} void Effects::setOverlayFlash(uint32_t c,unsigned long d){_overlay=OVERLAY_FLASH;_overlayFlashColor=c;_overlayStep=0;_overlayLastUpdate=millis();_overlayUntil=millis()+d;setBeep(2200,70);} void Effects::setOverlayStart(){_overlay=OVERLAY_START;_overlayStep=0;_overlayLastUpdate=millis();_overlayUntil=millis()+1000;setBeep(2600,1000);} void Effects::setOverlayStop(){_overlay=OVERLAY_STOP;_overlayStep=0;_overlayLastUpdate=millis();_overlayUntil=millis()+1000;setBeep(2600,1000);}
void Effects::setBlinker(BlinkerMode m){_blinker=m;_blinkerState=false;_blinkerLastUpdate=millis();} void Effects::setBeep(int f,unsigned long d){ledcWriteTone(PIEZO_CHANNEL,f);_beepUntil=millis()+d;}
void Effects::updateAnimation(){unsigned long n=millis();if(n-_animLastUpdate>=120){_animLastUpdate=n;_animStep++;}_pulseBrightness+=_pulseDirection;if(_pulseBrightness>=250||_pulseBrightness<=20)_pulseDirection*=-1;}
void Effects::updateOverlay(){if(_overlay!=OVERLAY_NONE&&millis()>_overlayUntil)_overlay=OVERLAY_NONE;if(millis()-_overlayLastUpdate>=100){_overlayLastUpdate=millis();_overlayStep++;}}
void Effects::updateBlinker(){if(millis()-_blinkerLastUpdate>=400){_blinkerLastUpdate=millis();_blinkerState=!_blinkerState;if(_blinkerState&&_blinker!=BLINK_NONE)setBeep(1800,30);}}
void Effects::updateBeep(){if(_beepUntil>0&&millis()>_beepUntil){ledcWriteTone(PIEZO_CHANNEL,0);_beepUntil=0;}}
void Effects::render(){clearAll();renderAnimation();renderOverlay();renderBlinker();_pixels.show();}
void Effects::renderAnimation(){switch(_anim){case ANIM_IDLE:renderAnimIdle();break;case ANIM_ERROR:renderAnimError();break;case ANIM_LINE:renderAnimLine();break;case ANIM_GAME:renderAnimGame();break;case ANIM_FREE:renderAnimFree();break;case ANIM_OBSTACLE:renderAnimObstacle();break;case ANIM_STOP:renderAnimStop();break;}}
void Effects::renderOverlay(){switch(_overlay){case OVERLAY_RFID:renderOverlayRfid();break;case OVERLAY_SUCCESS:renderOverlaySuccess();break;case OVERLAY_BOOT:renderOverlayBoot();break;case OVERLAY_FLASH:renderOverlayFlash();break;case OVERLAY_START:renderOverlayStart();break;case OVERLAY_STOP:renderOverlayStop();break;default:break;}}
void Effects::renderBlinker(){if(_blinker==BLINK_NONE||!_blinkerState)return;if(_blinker==BLINK_LEFT)setBlinkerLeds(true,false);else if(_blinker==BLINK_RIGHT)setBlinkerLeds(false,true);else if(_blinker==BLINK_BOTH)setBlinkerLeds(true,true);}
void Effects::renderAnimIdle(){setRoof(colorIdle(_pulseBrightness));} void Effects::renderAnimError(){uint8_t p=_animStep%ROOF_LED_COUNT;for(uint8_t i=0;i<ROOF_LED_COUNT;i++)setRoofPixel(i,i==p?colorError():0);} void Effects::renderAnimLine(){uint8_t p=_animStep%ROOF_LED_COUNT;for(uint8_t i=0;i<ROOF_LED_COUNT;i++)setRoofPixel(i,i==p?colorLine():0);} void Effects::renderAnimGame(){uint8_t p=_animStep%ROOF_LED_COUNT;for(uint8_t i=0;i<ROOF_LED_COUNT;i++)setRoofPixel(i,i==p?colorGame():0);} void Effects::renderAnimFree(){uint8_t p=_animStep%ROOF_LED_COUNT;for(uint8_t i=0;i<ROOF_LED_COUNT;i++)setRoofPixel(i,i==p?colorFree():0);}
void Effects::renderAnimObstacle(){bool s=(_animStep%2)==0;setRoofPixel(0,s?colorObstacle():0);setRoofPixel(3,s?colorObstacle():0);setRoofPixel(1,s?0:colorObstacle());setRoofPixel(2,s?0:colorObstacle());} void Effects::renderAnimStop(){bool s=(_animStep%2)==0;setRoofPixel(0,s?colorStop():0);setRoofPixel(3,s?colorStop():0);setRoofPixel(1,s?0:colorStop());setRoofPixel(2,s?0:colorStop());}
void Effects::renderOverlayRfid(){setRoof(colorRfid());} void Effects::renderOverlaySuccess(){setRoof(colorSuccess());} void Effects::renderOverlayStart(){setRoof(colorSuccess());} void Effects::renderOverlayStop(){setRoof(colorStop());} void Effects::renderOverlayBoot(){uint8_t p=_overlayStep%ROOF_LED_COUNT;for(uint8_t i=0;i<ROOF_LED_COUNT;i++)setRoofPixel(i,i==p?colorLine():0);} void Effects::renderOverlayFlash(){setRoof(_overlayFlashColor);}
void Effects::setRoof(uint32_t c){for(uint8_t i=0;i<ROOF_LED_COUNT;i++)setRoofPixel(i,c);} void Effects::setRoofPixel(uint8_t i,uint32_t c){if(i<ROOF_LED_COUNT)_pixels.setPixelColor(ROOF_LED_START+i,c);} void Effects::setBlinkerLeds(bool l,bool r){uint32_t c=colorBlinker();if(l)_pixels.setPixelColor(BLINKER_LEFT_LED,c);if(r)_pixels.setPixelColor(BLINKER_RIGHT_LED,c);} void Effects::clearAll(){_pixels.clear();}
uint32_t Effects::colorIdle(uint8_t b){return _pixels.Color(b,b,0);} uint32_t Effects::colorError(uint8_t b){return _pixels.Color(b,0,0);} uint32_t Effects::colorLine(){return _pixels.Color(0,0,255);} uint32_t Effects::colorGame(){return _pixels.Color(0,255,0);} uint32_t Effects::colorFree(){return _pixels.Color(255,180,0);} uint32_t Effects::colorObstacle(){return _pixels.Color(255,180,0);} uint32_t Effects::colorStop(){return _pixels.Color(255,0,0);} uint32_t Effects::colorSuccess(){return _pixels.Color(0,255,0);} uint32_t Effects::colorRfid(){return _pixels.Color(0,255,255);} uint32_t Effects::colorBlinker(){return _pixels.Color(255,120,0);}
